<?php
/**
 * Created by PhpStorm.
 * User: yezhilie
 * Date: 2019/8/26
 * Time: 14:53
 */

namespace AliyunOss\Controller;

use Common\Controller\AdminBase;

class BaseController extends AdminBase{

    protected function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 公共修改
     */
    public function updateTable(){
        $table = I('table','','trim'); //表
        $field = I('field','','trim'); //字段
        $value = I('value','','trim'); //值
        $where_name = I('where_name','trim'); //条件名称
        $where_value = I('where_value','','trim'); //添加的内容
        $save[$field] = $value;
        $where[$where_name] = $where_value;
        M($table)->where($where)->save($save);
        $this->ajaxReturn(self::createReturn(true, '','保存成功'));
    }

}